# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d974dcdb72ae31b60bb85179376fda6db99fa7307d3fb9f89f91999ec1805aab29af455c00443d17fd24a628b4445e47f693f8c03895281649361b3288dcd3d

test:
  secret_key_base: 5ea7a69ce5b9e57364c0b3f20a5e15c778ae10f30495f1cb412c57d4bffef4391e34f39d89543b68b5c47905ced9cd4abef7246c838e7ea76328ef27280e79e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
